### ISSUE TITLE
Подключение скриптов из node_modules

### ISSUE THREAD

**Issue by psuzanna** [abyss-soft/webpack-template-base#32]
Здравствуйте! Спасибо за сборку. 
Можете помочь с подключением модулей из node_modules?
Установила jquery, wowjs (не имеет значения, со всеми та же проблема). Подключаю в index.js 

`import "../node_modules/jquery/dist/jquery";
import "../node_modules/wowjs/dist/wow";
import "./js/common.js";

import "./assets/css/main.css";
import "./assets/scss/main.scss";

if (process.env.NODE_ENV !== `production`) {
  async function load() {
    let resize_info = await import("./smart-gread-layer/smart-gread-layer");
    resize_info.default();
  }
  load();
}`
но ни jquery, ни wowjs не подключаются , хотя код этих скриптов появляется в vendors , в app уже использование этих скриптов. 
[https://prnt.sc/OsEOaW8_4cV8](https://prnt.sc/OsEOaW8_4cV8) 
[https://prnt.sc/kcBo_32xNVYF](https://prnt.sc/kcBo_32xNVYF)

app идёт после vendors
Буду очень благодарна, если откликнитесь.

**Comment by abyss-soft** [comment]
@psuzanna все очень просто. Ставим например jquery:  **npm install jquery**
Официальная документация webpack говорит https://webpack.js.org/plugins/provide-plugin/
Значит надо в файл конфигурации (у нас это webpack.base.conf.js) добавить модуль :
 ````
new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
    }),
 ````
Получим вот такое:
 ````
 plugins: [
    new MiniCssExtractPlugin(....),
    new HtmlWebpackPlugin(....),
    new HtmlPluginRemove(.....),

    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
    }),
  ],
````
Больше нигде ничего подключать не надо, можно просто использовать. Например в файле **src/index.js**
````
$( ".logo" ).css( "border", "3px solid green" );
````

С другими модулями все аналогично.

**Comment by psuzanna** [comment]
Большое спасибо!
