### ISSUE TITLE
Неверный путь к изображениям в css

### ISSUE THREAD

**Issue by OZ1245** [abyss-soft/webpack-template-base#9]
После сборки в режиме разработки в css на выходе путь к изображениям выглядит как `background-image: url(image.png)` вместо ожидаемого `background-image: url(../img/image.png)`. 
После сборки в режиме продакшена изображения сохраняются в корень папки dist вместо `assets/img/`.
Что не так в этой сборке?

**Comment by abyss-soft** [comment]
В этой сборке все правильно.
Изображения сохраняются как и положено в папку `\dist\assets\img`
Смотрите внимательно на изначальную структуру ваших папок, а так же куда вы поместили ваши изображения, которые доступны в CSS.
Так же советую обратить внимание на  `"~": PATHS.src,`
